---
title: "Dashboard 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

** Need to use render function in r markdown to put it in output format in dashboard **
**Use rmarkdown::render("dashboard.Rmd",output_format="flexdashboard::flex_dashboard")**

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r include=FALSE}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
box_ggplot = 
  nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

### Chart C

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, 
          y = ~n, color = ~neighbourhood, 
          type = "bar", 
          colors = "viridis")
```

