---
title: "Dashboard 2: NYC Resturant Inspection Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

** Need to use render function in r markdown to put it in output format in dashboard **
**Use rmarkdown::render("dashboard_2.Rmd",output_format="flexdashboard::flex_dashboard")**

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(dplyr)
library(plotly)
library(stringr)
library(forcats)
```

```{r include=FALSE}

data("rest_inspec")
rest_inspec =
  rest_inspec|>
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |> 
  mutate(boro = str_to_title(boro))
```


Column {data-width=450}
-----------------------------------------------------------------------

### Chart 1:Pizza Places by Borough

```{r}
rest_inspec|> 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) |>
  group_by(boro) |>
  summarise(n = n(), .groups = 'drop') |>
  mutate(boro = fct_infreq(boro))|>
  plot_ly(x = ~boro, 
          y = ~n, color = ~boro, 
          type = "bar", 
          colors = "viridis")|>
  layout(xaxis = list(title = "Borough"),
         yaxis = list(title = "Number of Pizza Places"))

```

Column {data-width=250}
-----------------------------------------------------------------------

### Chart 2:Average Inspection Score and Number of Inspections by each Borough

```{r}
rest_inspec|> 
  mutate(
    boro = str_to_title(boro))|>
  group_by(dba, boro) |>
  summarize(
    avg_score = mean(score, na.rm = TRUE),
    n_inspections = n()
  ) |>
  ungroup()|>
  plot_ly(y = ~n_inspections,
          x = ~avg_score, color = ~boro,
          type = "scatter",mode = "markers",
          colors = "viridis")
```

### Chart 3: Distribution of Inspection Scores for each NYC Borough

```{r}
rest_inspec|>
  plot_ly(x = ~boro,
          y = ~score, color = ~boro,
          type = "box",
          colors = "viridis")|>
  layout(xaxis = list(title = "Borough"),
    yaxis = list(title = "Inspection Scores")
  )
  
```

